In [ ]:
import numpy as np

# Define a 5x5 matrix as input
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Calculate the convolution result (valid padding)
def convolution(input_matrix, filter_weights):
    input_height, input_width = input_matrix.shape
    filter_height, filter_width = filter_weights.shape
    output_height = input_height - filter_height + 1
    output_width = input_width - filter_width + 1
    output_matrix = np.zeros((output_height, output_width), dtype=np.float32)

    for i in range(output_height):
        for j in range(output_width):
            output_matrix[i, j] = np.sum(input_matrix[i:i+filter_height, j:j+filter_width] * filter_weights)

    return output_matrix

# Perform convolution
conv_result = convolution(input_matrix, filter_weights)

# Define a target matrix (gradients with respect to the input)
target_matrix = np.array([
    [10, 10, 10],
    [10, 10, 10],
    [10, 10, 10]
], dtype=np.float32)

# Calculate the error (difference between the convolution result and the target)
error = target_matrix - conv_result

# Print the results
print("Input Matrix:")
print(input_matrix)
print("\nFilter Weights:")
print(filter_weights)
print("\nConvolution Result:")
print(conv_result)
print("\nTarget Matrix:")
print(target_matrix)
print("\nError:")
print(error)


Input Matrix:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]

Filter Weights:
[[ 1.  0. -1.]
 [ 2.  0. -2.]
 [ 1.  0. -1.]]

Convolution Result:
[[-8. -8. -8.]
 [-8. -8. -8.]
 [-8. -8. -8.]]

Target Matrix:
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]

Error:
[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [ ]:
import numpy as np

# Define a 5x5 matrix as input
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Define a target matrix (gradients with respect to the input)
target_matrix = np.array([
    [10, 10, 10],
    [10, 10, 10],
    [10, 10, 10]
], dtype=np.float32)

# Hyperparameters
learning_rate = 0.001
epochs = 150000

input_matrix/= np.max(np.abs(input_matrix))

print(input_matrix)

# Perform gradient descent
for epoch in range(epochs):
    # Perform convolution
    conv_result = np.zeros_like(target_matrix, dtype=np.float32)
    for i in range(conv_result.shape[0]):
        for j in range(conv_result.shape[1]):
            conv_result[i, j] = np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights)

    # Calculate the error
    error = target_matrix - conv_result
    # print(error)
    # Calculate the gradient
    gradient = np.zeros_like(filter_weights, dtype=np.float32)
    listGradient=[]
    for i in range(gradient.shape[0]):
        for j in range(gradient.shape[1]):
            e = error[i,j]
            # print(e)
            gradient = e * -1 * 1 * input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]]
            # gradient /= np.max(np.abs(gradient))
            listGradient.append(gradient)
            # print(gradient)

    # Normalize the gradient
    # gradient /= np.max(np.abs(gradient))
    # gradient /= 16.0

    gradient=np.sum(listGradient, axis=0)
    # print(gradient)
    # print(10*'**********')
    # 1/0
    # Update the filter weights using gradient descent
    filter_weights = filter_weights - learning_rate * gradient

    # Print the loss every 10 epochs
    if epoch % 1000 == 0:
        loss = np.sum(error ** 2)
        print(f"Epoch {epoch}, Loss: {loss}")

# Print the final filter weights
print("\nFinal Filter Weights:")
print(filter_weights)

# Perform convolution with the trained filter on the original input_matrix
conv_result_original = np.zeros_like(target_matrix, dtype=np.float32)
for i in range(conv_result_original.shape[0]):
    for j in range(conv_result_original.shape[1]):
        conv_result_original[i, j] = np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights)

# Print the results
print("\nOriginal Input Matrix:")
print(input_matrix)
print("\nConvolution Result with Trained Filter on Original Input Matrix:")
print(conv_result_original)



[[0.04 0.08 0.12 0.16 0.2 ]
 [0.24 0.28 0.32 0.36 0.4 ]
 [0.44 0.48 0.52 0.56 0.6 ]
 [0.64 0.68 0.72 0.76 0.8 ]
 [0.84 0.88 0.92 0.96 1.  ]]
Epoch 0, Loss: 958.5215454101562
Epoch 1000, Loss: 51.490318298339844
Epoch 2000, Loss: 35.029136657714844
Epoch 3000, Loss: 23.830516815185547
Epoch 4000, Loss: 16.212013244628906
Epoch 5000, Loss: 11.029134750366211
Epoch 6000, Loss: 7.503177642822266
Epoch 7000, Loss: 5.104464054107666
Epoch 8000, Loss: 3.472597360610962
Epoch 9000, Loss: 2.362431049346924
Epoch 10000, Loss: 1.6071748733520508
Epoch 11000, Loss: 1.0933741331100464
Epoch 12000, Loss: 0.7438321709632874
Epoch 13000, Loss: 0.5060402154922485
Epoch 14000, Loss: 0.34426945447921753
Epoch 15000, Loss: 0.2342129349708557
Epoch 16000, Loss: 0.1593412458896637
Epoch 17000, Loss: 0.10841048508882523
Epoch 18000, Loss: 0.07376018911600113
Epoch 19000, Loss: 0.05018775537610054
Epoch 20000, Loss: 0.034149982035160065
Epoch 21000, Loss: 0.023239534348249435
Epoch 22000, Loss: 0.015816112980

In [ ]:
import numpy as np

# Define a 6x6 input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
], dtype=np.float32)

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Define a 4x4 target matrix (gradient with respect to the input)
target_matrix = np.array([
    [10, 10, 10, 10],
    [10, 10, 10, 10],
    [10, 10, 10, 10],
    [10, 10, 10, 10]
], dtype=np.float32)

# Hyperparameters
learning_rate = 0.001
epochs = 50000

input_matrix/= np.max(np.abs(input_matrix))

# ReLU activation function
def relu(x):
    return x

# Training
for epoch in range(epochs):
    # Perform convolution
    conv_result = np.zeros((4, 4), dtype=np.float32)
    for i in range(conv_result.shape[0]):
        for j in range(conv_result.shape[1]):
            conv_result[i, j] = (np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

    # Calculate the error
    error = target_matrix - conv_result

    listGradient=[]
    # Calculate the gradient
    gradient = np.zeros_like(filter_weights, dtype=np.float32)
    for i in range(gradient.shape[0]):
        for j in range(gradient.shape[1]):
            e = error[i,j]
            # print(e)
            gradient = e * -1 * 1 * input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]]
            # gradient /= np.max(np.abs(gradient))
            listGradient.append(gradient)
            # print(gradient)

    # Normalize the gradient
    # gradient /= np.max(np.abs(gradient))

    gradient=np.sum(listGradient, axis=0)

    # Update the filter weights using gradient descent
    filter_weights = filter_weights - learning_rate * gradient

    # Print the loss every 10 epochs
    if epoch % 100 == 0:
        loss = np.sum(error ** 2)
        print(f"Epoch {epoch}, Loss: {loss}")

# Print the final filter weights
print("\nFinal Filter Weights:")
print(filter_weights)

# Perform convolution with the trained filter and ReLU activation
conv_result_relu = np.zeros((4, 4), dtype=np.float32)
for i in range(conv_result_relu.shape[0]):
    for j in range(conv_result_relu.shape[1]):
        conv_result_relu[i, j] = relu(np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

# Print the results
print("\nInput Matrix:")
print(input_matrix)
print("\nTarget Matrix:")
print(target_matrix)
print("\nConvolution Result with Trained Filter and ReLU:")
print(conv_result_relu)


Epoch 0, Loss: 1600.0
Epoch 100, Loss: 168.84518432617188
Epoch 200, Loss: 219.87356567382812
Epoch 300, Loss: 233.87246704101562
Epoch 400, Loss: 231.31405639648438
Epoch 500, Loss: 225.63816833496094
Epoch 600, Loss: 219.5428466796875
Epoch 700, Loss: 213.51287841796875
Epoch 800, Loss: 207.63111877441406
Epoch 900, Loss: 201.90798950195312
Epoch 1000, Loss: 196.34234619140625
Epoch 1100, Loss: 190.92984008789062
Epoch 1200, Loss: 185.66651916503906
Epoch 1300, Loss: 180.54837036132812
Epoch 1400, Loss: 175.57130432128906
Epoch 1500, Loss: 170.73141479492188
Epoch 1600, Loss: 166.0249481201172
Epoch 1700, Loss: 161.4482421875
Epoch 1800, Loss: 156.9976806640625
Epoch 1900, Loss: 152.66978454589844
Epoch 2000, Loss: 148.46124267578125
Epoch 2100, Loss: 144.36868286132812
Epoch 2200, Loss: 140.3889617919922
Epoch 2300, Loss: 136.51890563964844
Epoch 2400, Loss: 132.75555419921875
Epoch 2500, Loss: 129.09591674804688
Epoch 2600, Loss: 125.53723907470703
Epoch 2700, Loss: 122.07666778564

In [ ]:
import numpy as np

# Define a 5x5 matrix as input
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Define a target matrix (gradients with respect to the input)
target_matrix = np.array([
    [10, 10, 10],
    [10, 10, 10],
    [10, 10, 10]
], dtype=np.float32)

# Hyperparameters
learning_rate = 0.001
epochs = 10000

# ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Perform gradient descent with ReLU activation
for epoch in range(epochs):
    # Perform convolution
    conv_result = np.zeros_like(target_matrix, dtype=np.float32)
    for i in range(conv_result.shape[0]):
        for j in range(conv_result.shape[1]):
            conv_result[i, j] = relu(np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

    # Calculate the error
    error = conv_result - target_matrix

    # Calculate the gradient
    gradient = np.zeros_like(filter_weights, dtype=np.float32)
    for i in range(gradient.shape[0]):
        for j in range(gradient.shape[1]):
            gradient[i, j] = np.sum(error * input_matrix[i:i+error.shape[0], j:j+error.shape[1]])

    # Normalize the gradient
    gradient /= np.max(np.abs(gradient))

    # Update the filter weights using gradient descent
    filter_weights -= learning_rate * gradient

    # Print the loss every 10 epochs
    if epoch % 1000 == 0:
        loss = np.sum(error ** 2)
        print(f"Epoch {epoch}, Loss: {loss}")

# Print the final filter weights
print("\nFinal Filter Weights:")
print(filter_weights)

# Perform convolution with the trained filter and ReLU activation on the original input_matrix
conv_result_original_relu = np.zeros_like(target_matrix, dtype=np.float32)
for i in range(conv_result_original_relu.shape[0]):
    for j in range(conv_result_original_relu.shape[1]):
        conv_result_original_relu[i, j] = relu(np.sum(input_matrix[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

# Print the results
print("\nOriginal Input Matrix:")
print(input_matrix)
print("\nConvolution Result with Trained Filter and ReLU on Original Input Matrix:")
print(conv_result_original_relu)


In [ ]:
import numpy as np

# Define two 5x5 matrices as input
input_matrix1 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

input_matrix2 = np.array([
    [5, 4, 3, 2, 1],
    [10, 9, 8, 7, 6],
    [15, 14, 13, 12, 11],
    [20, 19, 18, 17, 16],
    [25, 24, 23, 22, 21]
], dtype=np.float32)

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Define two target matrices (gradients with respect to the input)
target_matrix1 = np.array([
    [10, 10, 10],
    [10, 10, 10],
    [10, 10, 10]
], dtype=np.float32)

target_matrix2 = np.array([
    [5, 5, 5],
    [5, 5, 5],
    [5, 5, 5]
], dtype=np.float32)

# Hyperparameters
learning_rate = 0.001
epochs = 30000

# ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Training with input_matrix1 and target_matrix1
for epoch in range(epochs):
    # Perform convolution
    conv_result1 = np.zeros_like(target_matrix1, dtype=np.float32)
    for i in range(conv_result1.shape[0]):
        for j in range(conv_result1.shape[1]):
            conv_result1[i, j] = relu(np.sum(input_matrix1[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

    # Calculate the error
    error1 = conv_result1 - target_matrix1

    # Calculate the gradient
    gradient1 = np.zeros_like(filter_weights, dtype=np.float32)
    for i in range(gradient1.shape[0]):
        for j in range(gradient1.shape[1]):
            gradient1[i, j] = np.sum(error1 * input_matrix1[i:i+error1.shape[0], j:j+error1.shape[1]])

    # Normalize the gradient
    gradient1 /= np.max(np.abs(gradient1))

    # Update the filter weights using gradient descent
    filter_weights -= learning_rate * gradient1

    # Perform convolution
    conv_result2 = np.zeros_like(target_matrix2, dtype=np.float32)
    for i in range(conv_result2.shape[0]):
        for j in range(conv_result2.shape[1]):
            conv_result2[i, j] = relu(np.sum(input_matrix2[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

    # Calculate the error
    error2 = conv_result2 - target_matrix2

    # Calculate the gradient
    gradient2 = np.zeros_like(filter_weights, dtype=np.float32)
    for i in range(gradient2.shape[0]):
        for j in range(gradient2.shape[1]):
            gradient2[i, j] = np.sum(error2 * input_matrix2[i:i+error2.shape[0], j:j+error2.shape[1]])

    # Normalize the gradient
    gradient2 /= np.max(np.abs(gradient2))

    # Update the filter weights using gradient descent
    filter_weights -= learning_rate * gradient2

    # Print the loss every 10 epochs
    if epoch % 1000 == 0:
        loss2 = np.sum(error2 ** 2)+np.sum(error1 ** 2)
        print(f"Epoch {epoch} (Input 2, Target 2), Loss: {loss2}")

# Print the final filter weights
print("\nFinal Filter Weights:")
print(filter_weights)

# Perform convolution with the trained filter and ReLU activation on input_matrix1 and target_matrix1
conv_result1_relu = np.zeros_like(target_matrix1, dtype=np.float32)
for i in range(conv_result1_relu.shape[0]):
    for j in range(conv_result1_relu.shape[1]):
        conv_result1_relu[i, j] = relu(np.sum(input_matrix1[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

# Perform convolution with the trained filter and ReLU activation on input_matrix2 and target_matrix2
conv_result2_relu = np.zeros_like(target_matrix2, dtype=np.float32)
for i in range(conv_result2_relu.shape[0]):
    for j in range(conv_result2_relu.shape[1]):
        conv_result2_relu[i, j] = relu(np.sum(input_matrix2[i:i+filter_weights.shape[0], j:j+filter_weights.shape[1]] * filter_weights))

# Print the results
print("\nInput Matrix 1:")
print(input_matrix1)
print("\nConvolution Result with Trained Filter and ReLU on Input Matrix 1:")
print(conv_result1_relu)

print("\nInput Matrix 2:")
print(input_matrix2)
print("\nConvolution Result with Trained Filter and ReLU on Input Matrix 2:")
print(conv_result2_relu)


In [ ]:
import numpy as np

# Define five 5x5 matrices as input
input_matrix1 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

input_matrix2 = np.array([
    [5, 4, 3, 2, 1],
    [10, 9, 8, 7, 6],
    [15, 14, 13, 12, 11],
    [20, 19, 18, 17, 16],
    [25, 24, 23, 22, 21]
], dtype=np.float32)

input_matrix3 = np.array([
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [4, 4, 4, 4, 4],
    [5, 5, 5, 5, 5]
], dtype=np.float32)


# Concatenate input matrices into an array
input_matrices = np.array([input_matrix1, input_matrix2, input_matrix3])

# Define a 3x3 filter
filter_weights = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
], dtype=np.float32)

# Define five target matrices (gradients with respect to the input)
target_matrix1 = np.array([
    [10, 10, 10],
    [10, 10, 10],
    [10, 10, 10]
], dtype=np.float32)

target_matrix2 = np.array([
    [5, 5, 5],
    [5, 5, 5],
    [5, 5, 5]
], dtype=np.float32)

target_matrix3 = np.array([
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3]
], dtype=np.float32)



# Concatenate target matrices into an array
target_matrices = np.array([target_matrix1, target_matrix2, target_matrix3])

# Hyperparameters
learning_rate = 0.001
epochs = 150000

# ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Training for all input-target pairs
for epoch in range(epochs):
    total_loss = 0

    # Iterate over all input-target pairs
    for i in range(len(input_matrices)):
        # Get the current input and target matrices
        current_input_matrix = input_matrices[i]
        current_target_matrix = target_matrices[i]

        # Perform convolution
        conv_result = np.zeros_like(current_target_matrix, dtype=np.float32)
        for j in range(conv_result.shape[0]):
            for k in range(conv_result.shape[1]):
                conv_result[j, k] = relu(np.sum(current_input_matrix[j:j+filter_weights.shape[0], k:k+filter_weights.shape[1]] * filter_weights))

        # Calculate the error
        error = conv_result - current_target_matrix

        # Calculate the gradient
        gradient = np.zeros_like(filter_weights, dtype=np.float32)
        for j in range(gradient.shape[0]):
            for k in range(gradient.shape[1]):
                gradient[j, k] = np.sum(error * current_input_matrix[j:j+error.shape[0], k:k+error.shape[1]])

        # Normalize the gradient
        gradient /= np.max(np.abs(gradient))

        # Update the filter weights using gradient descent
        filter_weights -= learning_rate * gradient

        # Accumulate the loss
        total_loss += np.sum(error ** 2)

    # Print the average loss every 10 epochs
    if epoch % 3000 == 0:
        average_loss = total_loss / len(input_matrices)
        print(f"Epoch {epoch}, Average Loss: {average_loss}")

# Print the final filter weights
print("\nFinal Filter Weights:")
print(filter_weights)

# Perform convolution with the trained filter and ReLU activation on all input-target pairs
for i in range(len(input_matrices)):
    current_input_matrix = input_matrices[i]
    current_target_matrix = target_matrices[i]

    conv_result_relu = np.zeros_like(current_target_matrix, dtype=np.float32)
    for j in range(conv_result_relu.shape[0]):
        for k in range(conv_result_relu.shape[1]):
            conv_result_relu[j, k] = relu(np.sum(current_input_matrix[j:j+filter_weights.shape[0], k:k+filter_weights.shape[1]] * filter_weights))

    # Print the results
    print(f"\nInput Matrix {i+1}:")
    print(current_input_matrix)
    print(f"Convolution Result with Trained Filter and ReLU on Input Matrix {i+1}:")
    print(conv_result_relu)


Epoch 0, Average Loss: 394.31129201253253
Epoch 1000, Average Loss: 106.54151980082194
Epoch 2000, Average Loss: 83.59505716959636
Epoch 3000, Average Loss: 84.86994043986003
Epoch 4000, Average Loss: 84.72880045572917
Epoch 5000, Average Loss: 83.16801007588704
Epoch 6000, Average Loss: 81.09403165181477
Epoch 7000, Average Loss: 78.89711888631184
Epoch 8000, Average Loss: 76.7125924428304
Epoch 9000, Average Loss: 74.58285013834636
Epoch 10000, Average Loss: 72.52041943868001
Epoch 11000, Average Loss: 70.52784538269043
Epoch 12000, Average Loss: 68.60388310750325
Epoch 13000, Average Loss: 66.7471211751302
Epoch 14000, Average Loss: 64.95509020487468
Epoch 15000, Average Loss: 63.22580528259277
Epoch 16000, Average Loss: 61.557067235310875
Epoch 17000, Average Loss: 59.94713020324707
Epoch 18000, Average Loss: 58.39397048950195
Epoch 19000, Average Loss: 56.89552625020345

Final Filter Weights:
[[-2.7085752  -1.8693738  -1.0301826 ]
 [ 1.1135106   0.9527454   0.79195076]
 [ 2.935668